name: Publish packages

on:
  push:
    tags: ["*"]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish (must exist in repo)'
        required: true
        default: ''

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  github:
    uses: tree-sitter/workflows/.github/workflows/release.yml@main
    with:
      abi-version: 14
      attestations: true
  npm:
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    with:
      abi-version: 14
  crates:
    uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
    secrets:
      CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
    with:
      abi-version: 14
  pypi:
    uses: omeyenburg/tree-sitter-workflows/.github/workflows/package-pypi.yml@9850ddde85c69c69b0fdf9880f45a5f162f04579
    secrets:
      PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}
    with:
      abi-version: 14
